<?php

namespace Database\Seeders;

use App\Models\Articol;
use Illuminate\Database\Seeder;

class ArticolSeeder extends Seeder
{
    /**
     * 6 articole de blog cu continut SEO real (RO cu diacritice + DE/EN complete),
     * plus 10 articole extinse (RO, ~1000-1400 cuvinte) incarcate din
     * database/seeders/data/blog.json + database/seeders/data/blog/{slug}.md.
     * Link-urile interne folosesc sintaxa [text](/url) — randata de site/articol.
     */
    public function run(): void
    {
        $t = fn (string $ro, string $de, string $en): array => ['ro' => $ro, 'de' => $de, 'en' => $en];

        $rows = [
            [
                'slug' => 'metru-ster-vs-metru-cub-lemn-de-foc',
                'titlu' => $t(
                    'Metru ster vs metru cub la lemnul de foc: diferența pe înțelesul tuturor',
                    'Raummeter (Ster) vs. Festmeter bei Brennholz: der Unterschied, einfach erklärt',
                    'Stacked cubic meter (ster) vs solid cubic meter for firewood: the difference, explained simply',
                ),
                'excerpt' => $t(
                    'Sterul și metrul cub nu sunt același lucru — diferența poate însemna 35-40% din banii tăi. Uite cum le deosebești și cum verifici la recepție.',
                    'Ster und Festmeter sind nicht dasselbe — der Unterschied kann 35–40 % Ihres Geldes ausmachen. So unterscheiden Sie die beiden und prüfen die Menge bei der Lieferung.',
                    'A ster and a solid cubic meter are not the same thing — the difference can be 35–40% of your money. Here is how to tell them apart and check the quantity on delivery.',
                ),
                'continut' => $t(
                    "Când cumperi lemn de foc, prețul se exprimă fie în metri cubi, fie în metri steri. Diferența nu e un moft tehnic — e exact diferența dintre cât lemn primești și cât aer plătești.\n\nMetrul cub (m³) înseamnă lemn plin: un cub imaginar de 1x1x1 metri umplut complet cu masă lemnoasă, fără spații. Așa se măsoară buștenii și lemnul rotund în acte.\n\nMetrul ster înseamnă lemn stivuit: tot un cub de 1x1x1 metri, dar umplut cu lemne tăiate și crăpate, aranjate unele peste altele. Între bucăți rămân inevitabil spații de aer — iar aerul nu arde.\n\nFactorul de conversie practic: un ster conține aproximativ 0,6–0,65 m³ de lemn plin, în funcție de cât de drepte sunt lemnele, de lungimea lor și de cât de îngrijit e stivuită grămada. Cu alte cuvinte, ca să obții un metru cub de lemn plin, ai nevoie de circa un ster și jumătate.\n\nCum verifici la recepție: cere să se descarce lemnul stivuit, nu vrac — sau stivuiește-l tu înainte să confirmi cantitatea. Măsoară lungimea, înălțimea și adâncimea stivei și înmulțește-le. Dacă ai comandat 5 steri și stiva are 5 metri lungime, 1 metru înălțime și 1 metru adâncime, ești în regulă. La lemnul livrat vrac, volumul aparent e cu 30-40% mai mare decât cel stivuit — un camion care „arată plin\" nu garantează nimic.\n\nUn vânzător corect îți spune de la început în ce unitate vinde și cum poți verifica. Noi livrăm [lemn de foc](/lemn-de-foc) cântărit sau măsurat la ster, cu documente de proveniență — iar dacă vrei să verifici stiva la descărcare, șoferul te așteaptă.",
                    "Beim Kauf von Brennholz wird der Preis entweder pro Festmeter oder pro Raummeter (Ster) angegeben. Der Unterschied ist keine technische Spitzfindigkeit — er entscheidet darüber, wie viel Holz Sie erhalten und wie viel Luft Sie bezahlen.\n\nDer Festmeter (m³) bedeutet massives Holz: ein gedachter Würfel von 1x1x1 Metern, vollständig mit Holzmasse gefüllt, ohne Zwischenräume. So werden Stämme und Rundholz in den Dokumenten gemessen.\n\nDer Raummeter (Ster) bedeutet gestapeltes Holz: ebenfalls ein Würfel von 1x1x1 Metern, aber gefüllt mit gesägten und gespaltenen Scheiten, die aufeinandergeschichtet sind. Zwischen den Stücken bleiben zwangsläufig Lufträume — und Luft brennt nicht.\n\nDer praktische Umrechnungsfaktor: Ein Ster enthält etwa 0,6–0,65 m³ massives Holz, je nachdem, wie gerade die Scheite sind, wie lang sie sind und wie sorgfältig der Stapel geschichtet ist. Mit anderen Worten: Für einen Festmeter massives Holz benötigen Sie etwa anderthalb Ster.\n\nSo prüfen Sie bei der Lieferung: Lassen Sie das Holz gestapelt abladen, nicht lose geschüttet — oder stapeln Sie es selbst, bevor Sie die Menge bestätigen. Messen Sie Länge, Höhe und Tiefe des Stapels und multiplizieren Sie die Werte. Wenn Sie 5 Ster bestellt haben und der Stapel 5 Meter lang, 1 Meter hoch und 1 Meter tief ist, passt alles. Bei lose geliefertem Holz ist das scheinbare Volumen 30–40 % größer als gestapelt — ein LKW, der „voll aussieht\", garantiert gar nichts.\n\nEin fairer Verkäufer sagt Ihnen von Anfang an, in welcher Einheit er verkauft und wie Sie nachmessen können. Wir liefern [Brennholz](/lemn-de-foc) gewogen oder nach Ster gemessen, mit Herkunftsnachweisen — und wenn Sie den Stapel beim Abladen prüfen möchten, wartet der Fahrer gern.",
                    "When you buy firewood, the price is quoted either per solid cubic meter or per stacked cubic meter (ster). The difference is not a technicality — it is exactly the difference between how much wood you get and how much air you pay for.\n\nA solid cubic meter (m³) means solid wood: an imaginary 1x1x1 meter cube filled completely with wood, no gaps. This is how logs and roundwood are measured in official documents.\n\nA ster means stacked wood: the same 1x1x1 meter cube, but filled with cut and split logs arranged on top of each other. Air gaps inevitably remain between the pieces — and air doesn't burn.\n\nThe practical conversion factor: one ster contains roughly 0.6–0.65 m³ of solid wood, depending on how straight the logs are, how long they are and how carefully the stack is built. In other words, to get one solid cubic meter of wood, you need about a ster and a half.\n\nHow to check on delivery: ask for the wood to be unloaded stacked, not loose — or stack it yourself before confirming the quantity. Measure the length, height and depth of the stack and multiply them. If you ordered 5 sters and the stack is 5 meters long, 1 meter high and 1 meter deep, you're fine. Wood delivered loose has an apparent volume 30–40% larger than when stacked — a truck that \"looks full\" guarantees nothing.\n\nAn honest seller tells you upfront which unit they sell in and how you can check. We deliver [firewood](/lemn-de-foc) weighed or measured by the ster, with provenance documents — and if you want to check the stack at unloading, the driver will wait.",
                ),
                'categorie' => 'ghid',
                'imagine' => '/images/galle/proiecte/gramada-busteni-wide.webp',
                'published_at' => now()->subDays(34),
                'is_published' => true,
            ],
            [
                'slug' => 'fag-stejar-sau-carpen-ce-lemn-de-foc-alegi',
                'titlu' => $t(
                    'Ce lemn de foc e mai bun: fag, stejar sau carpen?',
                    'Welches Brennholz ist besser: Buche, Eiche oder Hainbuche?',
                    'Which firewood is best: beech, oak or hornbeam?',
                ),
                'excerpt' => $t(
                    'Toate trei sunt esențe tari și ard bine — dar fiecare are particularități. Comparație practică, plus când are sens să combini cu esențe moi.',
                    'Alle drei sind Harthölzer und brennen gut — doch jedes hat seine Eigenheiten. Ein praktischer Vergleich, plus wann es sinnvoll ist, mit Weichholz zu kombinieren.',
                    'All three are hardwoods and burn well — but each has its quirks. A practical comparison, plus when it makes sense to combine them with softwoods.',
                ),
                'continut' => $t(
                    "Fagul, stejarul și carpenul sunt cele trei esențe tari clasice pentru încălzit în România. Toate au densitate mare și ardere de durată — dar nu sunt identice.\n\nCarpenul e campionul puterii calorice: aproximativ 4,2–4,3 kWh/kg, cea mai densă esență folosită curent la foc. Arde lent, face jar consistent și ține căldura ore întregi. Dezavantaj: se aprinde mai greu și se despică mai dificil.\n\nStejarul vine imediat după: ~4,2 kWh/kg, ardere lentă și jar de durată. Conține taninuri, deci are nevoie de uscare mai lungă (ideal doi ani) ca să ardă curat. Uscat corect, e excelent pentru cazane și sobe cu acumulare.\n\nFagul e cel mai echilibrat: ~4,0 kWh/kg, se aprinde ușor, arde uniform, cu flacără frumoasă — motiv pentru care e preferatul șemineelor. Se usucă mai repede decât stejarul și se despică ușor.\n\nCând combini cu esențe moi: lemnul moale (plop, salcie, brad) arde repede și face flacără mare, dar jar puțin. E util la aprindere și la încălzirea rapidă a unei încăperi reci — aprinzi cu esență moale, întreții cu esență tare. Pentru foc continuu peste noapte, esența tare e singura alegere corectă.\n\nConcluzia practică: pentru cazan sau sobă cu acumulare — carpen sau stejar; pentru șemineu și ardere la vedere — fag; pentru buget echilibrat — un amestec de esențe tari funcționează foarte bine.\n\nVerifică mereu umiditatea: orice esență, oricât de nobilă, arde prost și murdar peste 20% umiditate. Vezi ce avem pe stoc la [lemn de foc](/lemn-de-foc) — stejar, carpen și fag, tăiat și crăpat, livrat în Prahova, Ilfov și București.",
                    "Buche, Eiche und Hainbuche sind die drei klassischen Harthölzer zum Heizen in Rumänien. Alle haben eine hohe Dichte und eine lange Brenndauer — aber identisch sind sie nicht.\n\nDie Hainbuche ist der Champion beim Heizwert: etwa 4,2–4,3 kWh/kg, das dichteste regelmäßig als Brennholz verwendete Holz. Sie brennt langsam, bildet kräftige Glut und hält die Wärme stundenlang. Nachteil: Sie ist schwerer zu entzünden und schwieriger zu spalten.\n\nDie Eiche folgt direkt danach: ~4,2 kWh/kg, langsamer Abbrand und langanhaltende Glut. Sie enthält Gerbstoffe (Tannine) und braucht daher eine längere Trocknung (ideal zwei Jahre), um sauber zu brennen. Richtig getrocknet ist sie hervorragend für Kessel und Speicheröfen.\n\nDie Buche ist die ausgewogenste: ~4,0 kWh/kg, leicht zu entzünden, gleichmäßiger Abbrand mit schönem Flammenbild — deshalb ist sie der Favorit für Kamine. Sie trocknet schneller als Eiche und lässt sich leicht spalten.\n\nWann Sie mit Weichholz kombinieren: Weichholz (Pappel, Weide, Tanne) brennt schnell mit großer Flamme, bildet aber wenig Glut. Es eignet sich zum Anzünden und zum schnellen Aufheizen eines kalten Raums — mit Weichholz anzünden, mit Hartholz weiterheizen. Für ein durchgehendes Feuer über Nacht ist Hartholz die einzig richtige Wahl.\n\nDas praktische Fazit: für Kessel oder Speicherofen — Hainbuche oder Eiche; für Kamin und sichtbares Feuer — Buche; bei ausgewogenem Budget funktioniert eine Mischung aus Harthölzern sehr gut.\n\nPrüfen Sie immer die Feuchtigkeit: Jedes Holz, so edel es auch sein mag, brennt über 20 % Feuchte schlecht und schmutzig. Sehen Sie, was wir bei [Brennholz](/lemn-de-foc) auf Lager haben — Eiche, Hainbuche und Buche, gesägt und gespalten, geliefert in Prahova, Ilfov und Bukarest.",
                    "Beech, oak and hornbeam are the three classic hardwoods for heating in Romania. All are dense and slow-burning — but they are not identical.\n\nHornbeam is the heating-value champion: roughly 4.2–4.3 kWh/kg, the densest species in common use for firewood. It burns slowly, makes substantial embers and holds heat for hours. Downside: it is harder to light and harder to split.\n\nOak comes right after: ~4.2 kWh/kg, slow burn and long-lasting embers. It contains tannins, so it needs longer seasoning (ideally two years) to burn cleanly. Properly dried, it is excellent for boilers and heat-retaining stoves.\n\nBeech is the most balanced: ~4.0 kWh/kg, easy to light, burns evenly with a beautiful flame — which is why it is the favourite for fireplaces. It dries faster than oak and splits easily.\n\nWhen to combine with softwoods: softwood (poplar, willow, fir) burns fast with a big flame but leaves little ember. It is useful for lighting and for quickly warming a cold room — light with softwood, sustain with hardwood. For a continuous overnight fire, hardwood is the only right choice.\n\nThe practical conclusion: for a boiler or heat-retaining stove — hornbeam or oak; for a fireplace and a visible flame — beech; on a balanced budget, a mix of hardwoods works very well.\n\nAlways check the moisture: any species, however noble, burns poorly and dirtily above 20% moisture. See what we have in stock at [firewood](/lemn-de-foc) — oak, hornbeam and beech, cut and split, delivered in Prahova, Ilfov and Bucharest.",
                ),
                'categorie' => 'ghid',
                'imagine' => '/images/galle/proiecte/depozit-amurg-wide.webp',
                'published_at' => now()->subDays(27),
                'is_published' => true,
            ],
            [
                'slug' => 'cat-lemn-de-foc-pentru-o-iarna',
                'titlu' => $t(
                    'Cât lemn de foc îți trebuie pentru o iarnă?',
                    'Wie viel Brennholz brauchen Sie für einen Winter?',
                    'How much firewood do you need for a winter?',
                ),
                'excerpt' => $t(
                    'Estimare orientativă pe tipuri de locuință și sisteme de încălzire — plus regula simplă cu care calculezi necesarul propriu.',
                    'Orientierungswerte nach Haustyp und Heizsystem — plus die einfache Faustregel, mit der Sie Ihren eigenen Bedarf berechnen.',
                    'Ballpark estimates by home type and heating system — plus the simple rule of thumb for working out your own needs.',
                ),
                'continut' => $t(
                    "Întrebarea pe care o primim cel mai des toamna: „câți steri să iau?\". Răspunsul corect depinde de trei lucruri — cât de mare e spațiul încălzit, cât de bine e izolat și cu ce arzi.\n\nRepere orientative pentru un sezon rece (noiembrie–martie):\n\nApartament sau casă mică (50–80 m²), încălzită cu o sobă bună: 4–6 steri de esență tare. Dacă soba e veche și fără acumulare, adaugă 1-2 steri.\n\nCasă medie (100–140 m²) cu centrală pe lemne sau două sobe: 8–12 steri. Izolația face diferența mare aici — o casă neizolată poate consuma ușor și 15.\n\nCasă mare (peste 150 m²) cu cazan pe lemne: 12–18 steri, în funcție de izolație și de temperatura de confort.\n\nRegula simplă de calcul: pornește de la consumul iernii trecute. Dacă nu-l știi, estimează 1 ster la 10-12 m² pentru o locuință mediu izolată cu sobă clasică, apoi ajustează după primul sezon. Mai bine să-ți rămână un ster decât să rămâi fără în ianuarie, când prețurile sunt maxime și livrările lente.\n\nCâteva sfaturi care reduc consumul: arde doar lemn uscat (sub 20% umiditate) — lemnul verde pierde până la o treime din căldură evaporând apa; curăță coșul înainte de sezon; nu sufoca focul — arderea înăbușită murdărește coșul și risipește lemnul.\n\nLa noi nu există cantitate minimă de comandă — poți lua și un singur ster, de probă, să vezi calitatea. Folosește [calculatorul de preț](/lemn-de-foc) ca să afli pe loc cât te costă necesarul tău, cu livrare în Prahova, Ilfov și București, sau [trimite-ne o comandă](/lemn-de-foc) direct din pagină.",
                    "Die Frage, die wir im Herbst am häufigsten hören: „Wie viele Ster soll ich nehmen?\". Die richtige Antwort hängt von drei Dingen ab — wie groß die beheizte Fläche ist, wie gut sie gedämmt ist und womit Sie heizen.\n\nOrientierungswerte für eine Heizsaison (November–März):\n\nWohnung oder kleines Haus (50–80 m²), beheizt mit einem guten Ofen: 4–6 Ster Hartholz. Ist der Ofen alt und ohne Wärmespeicherung, rechnen Sie 1–2 Ster dazu.\n\nMittleres Haus (100–140 m²) mit Holzkessel oder zwei Öfen: 8–12 Ster. Die Dämmung macht hier den großen Unterschied — ein ungedämmtes Haus kann leicht auch 15 verbrauchen.\n\nGroßes Haus (über 150 m²) mit Holzkessel: 12–18 Ster, je nach Dämmung und Wohlfühltemperatur.\n\nDie einfache Faustregel: Gehen Sie vom Verbrauch des letzten Winters aus. Kennen Sie ihn nicht, rechnen Sie mit 1 Ster pro 10–12 m² für ein durchschnittlich gedämmtes Haus mit klassischem Ofen und passen Sie nach der ersten Saison an. Besser, es bleibt ein Ster übrig, als dass Sie im Januar ohne dastehen, wenn die Preise am höchsten sind und die Lieferungen am langsamsten.\n\nEin paar Tipps, die den Verbrauch senken: Verbrennen Sie nur trockenes Holz (unter 20 % Feuchte) — grünes Holz verliert bis zu ein Drittel der Wärme durch das Verdampfen des Wassers; reinigen Sie den Schornstein vor der Saison; ersticken Sie das Feuer nicht — gedrosselter Abbrand verrußt den Schornstein und verschwendet Holz.\n\nBei uns gibt es keine Mindestbestellmenge — Sie können auch einen einzigen Ster zur Probe nehmen, um die Qualität zu prüfen. Nutzen Sie den [Preisrechner](/lemn-de-foc), um sofort zu erfahren, was Ihr Bedarf kostet — mit Lieferung in Prahova, Ilfov und Bukarest — oder [senden Sie uns eine Bestellung](/lemn-de-foc) direkt von der Seite.",
                    "The question we hear most often in autumn: \"how many sters should I get?\". The right answer depends on three things — how big the heated space is, how well it is insulated and what you burn the wood in.\n\nBallpark figures for a cold season (November–March):\n\nA flat or small house (50–80 m²) heated with a good stove: 4–6 sters of hardwood. If the stove is old, with no heat retention, add 1–2 sters.\n\nA medium house (100–140 m²) with a wood-fired boiler or two stoves: 8–12 sters. Insulation makes the big difference here — an uninsulated house can easily use 15.\n\nA large house (over 150 m²) with a wood boiler: 12–18 sters, depending on insulation and comfort temperature.\n\nThe simple rule of thumb: start from last winter's usage. If you don't know it, estimate 1 ster per 10–12 m² for an averagely insulated home with a classic stove, then adjust after the first season. Better to have a ster left over than to run out in January, when prices peak and deliveries slow down.\n\nA few tips that cut consumption: burn only dry wood (under 20% moisture) — green wood loses up to a third of its heat evaporating water; sweep the chimney before the season; don't choke the fire — smouldering dirties the chimney and wastes wood.\n\nWe have no minimum order — you can take a single ster as a trial, to see the quality. Use the [price calculator](/lemn-de-foc) to find out on the spot what your needs will cost, with delivery in Prahova, Ilfov and Bucharest, or [send us an order](/lemn-de-foc) straight from the page.",
                ),
                'categorie' => 'ghid',
                'imagine' => '/images/galle/proiecte/camion-incarcat-wide.webp',
                'published_at' => now()->subDays(20),
                'is_published' => true,
            ],
            [
                'slug' => 'vreau-sa-vand-padure-pasii-corecti',
                'titlu' => $t(
                    'Vreau să vând pădure: pașii corecți pentru un proprietar',
                    'Ich möchte Wald verkaufen: die richtigen Schritte für Eigentümer',
                    'Selling your forest: the right steps for an owner',
                ),
                'excerpt' => $t(
                    'De la actele de proprietate la APV și plata finală — ce trebuie să știi ca să-ți valorifici pădurea corect și legal, fără surprize.',
                    'Von den Eigentumsunterlagen über das APV bis zur letzten Zahlung — was Sie wissen müssen, um Ihren Wald korrekt und legal zu verwerten, ohne Überraschungen.',
                    'From ownership documents to the APV and the final payment — what you need to know to sell your forest properly and legally, with no surprises.',
                ),
                'continut' => $t(
                    "Ai moștenit sau deții o pădure și vrei să o valorifici? Procesul e mai simplu decât pare, dacă îl iei în ordinea corectă.\n\nPasul 1 — clarifică proprietatea. Ai nevoie de actele de proprietate (titlu, extras de carte funciară) și de identificarea exactă a parcelei. Dacă moștenirea nu e dezbătută, începe cu succesiunea — nimeni nu poate cumpăra legal de la un proprietar neclarificat.\n\nPasul 2 — evaluarea. Un cumpărător serios vine la fața locului și se uită la: specii (stejarul și fagul valorează mai mult decât plopul), vârsta și diametrul arborilor, volumul estimat, panta și accesul (un drum forestier bun poate crește prețul semnificativ). Cere evaluarea în scris.\n\nPasul 3 — APV-ul. Recoltarea legală se face doar pe baza unui act de punere în valoare (APV), întocmit prin ocolul silvic: arborii sunt marcați, măsurați și inventariați într-o partidă. APV-ul îți spune negru pe alb ce volum se recoltează — e protecția ta principală împotriva subevaluării.\n\nPasul 4 — alege forma de vânzare. Pe picior: vinzi arborii nerecoltați, cumpărătorul se ocupă de tot (exploatare, transport, acte) — tu primești banii și atât. Fasonat: recoltezi tu (sau plătești un prestator) și vinzi lemnul gata tăiat, la drum auto — preț mai bun pe metru cub, dar și risc și bătăi de cap mai mari. Pentru majoritatea proprietarilor mici, vânzarea pe picior e alegerea practică.\n\nPasul 5 — verifică-ți cumpărătorul. Cere: atestat de exploatare valabil, contract scris cu preț ferm și termene de plată, dovada că lucrează cu SUMAL (sistemul de trasabilitate a lemnului). Evită înțelegerile verbale și avansurile „pe încredere\".\n\nNoi [cumpărăm masă lemnoasă](/servicii/achizitie-masa-lemnoasa) pe picior sau fasonată, cu evaluare gratuită la fața locului, contract și plată prin bancă — iar de partea tehnică se ocupă echipa noastră de [exploatare forestieră](/servicii/exploatare-forestiera).",
                    "Sie haben einen Wald geerbt oder besitzen einen und möchten ihn verwerten? Der Prozess ist einfacher, als er scheint — wenn Sie ihn in der richtigen Reihenfolge angehen.\n\nSchritt 1 — Eigentum klären. Sie benötigen die Eigentumsunterlagen (Eigentumstitel, Grundbuchauszug) und die genaue Identifizierung der Parzelle. Ist die Erbschaft noch nicht geregelt, beginnen Sie mit dem Nachlassverfahren — niemand kann legal von einem ungeklärten Eigentümer kaufen.\n\nSchritt 2 — die Bewertung. Ein seriöser Käufer kommt vor Ort und prüft: Baumarten (Eiche und Buche sind mehr wert als Pappel), Alter und Durchmesser der Bäume, das geschätzte Volumen, Hangneigung und Zugänglichkeit (eine gute Forststraße kann den Preis deutlich erhöhen). Verlangen Sie die Bewertung schriftlich.\n\nSchritt 3 — das APV. Die legale Ernte erfolgt nur auf Grundlage eines APV (das amtliche Dokument zur Holzaufnahme und -bewertung), erstellt über das Forstamt: Die Bäume werden markiert, vermessen und in einem Los inventarisiert. Das APV sagt Ihnen schwarz auf weiß, welches Volumen geerntet wird — Ihr wichtigster Schutz vor Unterbewertung.\n\nSchritt 4 — Verkaufsform wählen. Stehend (auf dem Stamm): Sie verkaufen die nicht geernteten Bäume, der Käufer kümmert sich um alles (Ernte, Transport, Dokumente) — Sie erhalten das Geld, mehr nicht. Aufgearbeitet: Sie ernten selbst (oder beauftragen einen Dienstleister) und verkaufen das fertig geschnittene Holz an der Forststraße — besserer Preis pro Kubikmeter, aber auch mehr Risiko und Aufwand. Für die meisten kleinen Eigentümer ist der Verkauf auf dem Stamm die praktische Wahl.\n\nSchritt 5 — prüfen Sie Ihren Käufer. Verlangen Sie: eine gültige Erntezulassung, einen schriftlichen Vertrag mit festem Preis und Zahlungsfristen, den Nachweis, dass mit SUMAL (dem rumänischen Holz-Rückverfolgbarkeitssystem) gearbeitet wird. Vermeiden Sie mündliche Absprachen und Vorschüsse „auf Vertrauensbasis\".\n\nWir [kaufen Holz](/servicii/achizitie-masa-lemnoasa) — stehend oder aufgearbeitet — mit kostenloser Bewertung vor Ort, Vertrag und Zahlung per Bank; um die technische Seite kümmert sich unser Team für [Holzernte](/servicii/exploatare-forestiera).",
                    "Have you inherited or do you own a forest and want to sell it? The process is simpler than it looks, if you take it in the right order.\n\nStep 1 — clarify ownership. You need the ownership documents (title deed, land registry extract) and the exact identification of the parcel. If the inheritance hasn't been settled, start with the succession — nobody can legally buy from an unclarified owner.\n\nStep 2 — the valuation. A serious buyer comes on site and looks at: species (oak and beech are worth more than poplar), the age and diameter of the trees, the estimated volume, the slope and the access (a good forest road can raise the price significantly). Ask for the valuation in writing.\n\nStep 3 — the APV. Legal harvesting is only done based on an APV (the official harvesting valuation document), drawn up through the forest district office: the trees are marked, measured and inventoried into a lot. The APV tells you in black and white what volume will be harvested — your main protection against undervaluation.\n\nStep 4 — choose how to sell. Standing: you sell the unharvested trees and the buyer handles everything (harvesting, transport, paperwork) — you receive the money, and that's it. Processed: you harvest yourself (or pay a contractor) and sell the cut timber at the roadside — a better price per cubic meter, but more risk and more hassle. For most small owners, selling standing timber is the practical choice.\n\nStep 5 — vet your buyer. Ask for: a valid harvesting licence, a written contract with a firm price and payment deadlines, and proof that they work with SUMAL (Romania's timber traceability system). Avoid verbal deals and \"good faith\" advances.\n\nWe [buy timber](/servicii/achizitie-masa-lemnoasa) standing or processed, with a free on-site valuation, a contract and payment by bank transfer — and the technical side is handled by our [timber harvesting](/servicii/exploatare-forestiera) team.",
                ),
                'categorie' => 'ghid',
                'imagine' => '/images/galle/proiecte/busteni-marcati-wide.webp',
                'published_at' => now()->subDays(13),
                'is_published' => true,
            ],
            [
                'slug' => 'ce-inseamna-apv-si-de-ce-conteaza',
                'titlu' => $t(
                    'Ce înseamnă APV și de ce contează',
                    'Was das APV bedeutet und warum es zählt',
                    'What the APV means and why it matters',
                ),
                'excerpt' => $t(
                    'Actul de punere în valoare e documentul care face diferența între recoltare legală și tăiere ilegală. Ce conține și ce primește proprietarul.',
                    'Das APV ist das Dokument, das legale Holzernte von illegalem Einschlag unterscheidet. Was es enthält und was der Eigentümer erhält.',
                    'The harvesting valuation document (APV) is what separates legal harvesting from illegal logging. What it contains and what the owner receives.',
                ),
                'continut' => $t(
                    "APV — actul de punere în valoare — e documentul tehnic fără de care niciun arbore nu se taie legal în România. Dacă deții pădure sau cumperi lemn, merită să înțelegi ce face.\n\nCe este, concret: APV-ul e inventarul oficial al arborilor destinați recoltării dintr-o parcelă. Îl întocmește personalul silvic autorizat (de regulă prin ocolul silvic): arborii sunt aleși conform amenajamentului silvic, marcați cu ciocanul silvic — marca rotundă pe care o vezi pe trunchiuri — măsurați și înregistrați. Rezultatul e o „partidă\": lista cu specii, număr de arbori, volume estimate pe sortimente.\n\nDe ce contează pentru proprietar: APV-ul îți spune exact ce volum de lemn se recoltează din pădurea ta — baza corectă pentru orice negociere de preț. Fără APV, „vânzarea\" e o estimare după ochi, aproape întotdeauna în defavoarea ta. Tot APV-ul e și documentul care dovedește că recoltarea respectă amenajamentul — adică pădurea ta rămâne pădure, gestionată, nu rasă.\n\nDe ce contează pentru cumpărătorul de lemn: lemnul cu proveniență legală se trasează de la APV, prin autorizația de exploatare, până la avizele de însoțire generate în SUMAL la fiecare transport. Când cumperi lemn de foc cu acte, lanțul ăsta e garanția că nu finanțezi tăieri ilegale.\n\nCe primește proprietarul, pe scurt: partida (lista APV) cu volumele pe specii; autorizația de exploatare emisă înainte de începerea lucrării; procesul-verbal de predare a parchetului la final — dovada că terenul a fost lăsat curat, conform regulilor.\n\nDacă ești la prima exploatare și hârtiile te sperie, e normal — sunt multe și au termene. Echipa noastră de [exploatare forestieră](/servicii/exploatare-forestiera) lucrează doar cu acte complete și te ghidează pas cu pas, împreună cu ocolul silvic, de la marcarea arborilor până la predarea parchetului.",
                    "Das APV — das amtliche Dokument zur Holzaufnahme und -bewertung — ist das technische Dokument, ohne das in Rumänien kein Baum legal gefällt wird. Wenn Sie Wald besitzen oder Holz kaufen, lohnt es sich zu verstehen, was es leistet.\n\nWas es konkret ist: Das APV ist das amtliche Inventar der zur Ernte bestimmten Bäume einer Parzelle. Es wird von autorisiertem Forstpersonal erstellt (in der Regel über das Forstamt): Die Bäume werden gemäß der Forsteinrichtung ausgewählt, mit dem Forsthammer markiert — das runde Zeichen, das Sie an den Stämmen sehen —, vermessen und erfasst. Das Ergebnis ist ein „Los\": die Liste mit Baumarten, Stückzahl und geschätzten Volumen je Sortiment.\n\nWarum es für den Eigentümer zählt: Das APV sagt Ihnen genau, welches Holzvolumen aus Ihrem Wald geerntet wird — die korrekte Grundlage für jede Preisverhandlung. Ohne APV ist der „Verkauf\" eine Schätzung nach Augenmaß, fast immer zu Ihrem Nachteil. Das APV ist zugleich das Dokument, das belegt, dass die Ernte der Forsteinrichtung entspricht — Ihr Wald bleibt also Wald: bewirtschaftet, nicht kahlgeschlagen.\n\nWarum es für den Holzkäufer zählt: Holz mit legaler Herkunft lässt sich vom APV über die Erntegenehmigung bis zu den bei jedem Transport in SUMAL erstellten Begleitpapieren zurückverfolgen. Wenn Sie Brennholz mit Dokumenten kaufen, ist diese Kette die Garantie, dass Sie keine illegalen Fällungen finanzieren.\n\nWas der Eigentümer erhält, kurz gefasst: das Los (die APV-Liste) mit den Volumen je Baumart; die vor Beginn der Arbeiten ausgestellte Erntegenehmigung; das Übergabeprotokoll des Hiebsorts am Ende — der Nachweis, dass das Gelände sauber und regelkonform hinterlassen wurde.\n\nWenn dies Ihre erste Ernte ist und der Papierkram Sie abschreckt: Das ist normal — es sind viele Dokumente mit Fristen. Unser Team für [Holzernte](/servicii/exploatare-forestiera) arbeitet ausschließlich mit vollständigen Dokumenten und begleitet Sie Schritt für Schritt, gemeinsam mit dem Forstamt — von der Markierung der Bäume bis zur Übergabe des Hiebsorts.",
                    "The APV — the official harvesting valuation document — is the technical document without which no tree is legally felled in Romania. If you own forest or buy wood, it's worth understanding what it does.\n\nWhat it is, concretely: the APV is the official inventory of the trees designated for harvesting on a parcel. It is drawn up by authorised forestry staff (usually through the forest district office): the trees are chosen according to the forest management plan, marked with the forestry hammer — the round mark you see on the trunks — measured and recorded. The result is a \"lot\": the list of species, number of trees and estimated volumes by assortment.\n\nWhy it matters for the owner: the APV tells you exactly what volume of timber will be harvested from your forest — the correct basis for any price negotiation. Without an APV, the \"sale\" is an estimate by eye, almost always to your disadvantage. The APV is also the document proving the harvest follows the management plan — meaning your forest stays a forest: managed, not razed.\n\nWhy it matters for the wood buyer: legally sourced timber can be traced from the APV, through the harvesting permit, to the transport documents generated in SUMAL for every load. When you buy documented firewood, that chain is your guarantee that you are not funding illegal logging.\n\nWhat the owner receives, in short: the lot (the APV list) with volumes by species; the harvesting permit issued before work begins; the site handover report at the end — proof that the land was left clean, by the rules.\n\nIf this is your first harvest and the paperwork scares you, that's normal — there is a lot of it, with deadlines. Our [timber harvesting](/servicii/exploatare-forestiera) team works only with complete documents and guides you step by step, together with the forest district office, from tree marking to the site handover.",
                ),
                'categorie' => 'ghid',
                'imagine' => '/images/galle/proiecte/harvester-galle-wide.webp',
                'published_at' => now()->subDays(7),
                'is_published' => true,
            ],
            [
                'slug' => 'defrisare-teren-sau-curatare-vegetatie-diferenta',
                'titlu' => $t(
                    'Defrișare teren sau curățare vegetație? Diferența practică și legală',
                    'Rodung oder Vegetationsräumung? Der praktische und rechtliche Unterschied',
                    'Land clearing or vegetation removal? The practical and legal difference',
                ),
                'excerpt' => $t(
                    'Nu orice teren cu copaci e „pădure\" în acte — iar diferența schimbă tot: autorizații, costuri, termene. Ghid scurt ca să știi în ce situație ești.',
                    'Nicht jedes Grundstück mit Bäumen ist in den Dokumenten „Wald\" — und dieser Unterschied ändert alles: Genehmigungen, Kosten, Fristen. Ein kurzer Leitfaden, damit Sie wissen, wo Sie stehen.',
                    'Not every plot with trees is \"forest\" on paper — and the difference changes everything: permits, costs, timelines. A short guide so you know which situation you are in.',
                ),
                'continut' => $t(
                    "„Vreau să defrișez un teren\" — așa începe aproape orice discuție. Dar legal și practic, contează enorm un singur lucru: terenul e fond forestier sau nu?\n\nTeren neforestier cu vegetație: o pășune năpădită de arbuști, o livadă abandonată, un teren intravilan cu copaci crescuți sălbatic, un teren agricol lăsat în paragină. Aici vorbim despre curățare de vegetație — lucrare pe care o poți face ca proprietar, în general fără autorizații silvice. Tai vegetația, scoți cioatele, frezezi rădăcinile, nivelezi — și terenul e gata pentru construcție sau agricultură. Pentru arbori izolați din intravilan, unele primării cer un aviz de tăiere — un drum scurt la primărie te lămurește.\n\nFond forestier: dacă terenul figurează în acte ca pădure (fond forestier național), regulile se schimbă radical. Scoaterea din fondul forestier e o procedură de excepție — lungă, costisitoare și cu compensări — iar tăierea fără ea înseamnă infracțiune, indiferent că ești proprietar. Aici nu există scurtături: orice intervenție trece prin ocolul silvic și prin amenajament.\n\nCum afli în ce situație ești: verifică extrasul de carte funciară la rubrica de folosință (pădure / pășune / arabil / curți-construcții). La dubii, întreabă ocolul silvic pe raza căruia e terenul — gratuit și rapid.\n\nCe presupune curățarea profesionistă de teren: tăierea și tocarea vegetației, scosul cioatelor (smulgere sau frezare — frezarea mărunțește cioata sub nivelul solului, fără cratere), strângerea și valorificarea materialului lemnos, nivelarea finală. Cu utilaje dedicate, un teren de casă se curăță în zile, nu în săptămâni.\n\nNoi facem [curățare și defrișare de terenuri](/servicii/curatare-terenuri) neforestiere fără suprafață minimă — de la o curte cu câțiva pomi până la hectare întregi — iar dacă terenul tău se dovedește fond forestier, îți spunem direct și te orientăm către procedura corectă, nu către o lucrare care te bagă în belea.",
                    "„Ich möchte ein Grundstück roden\" — so beginnt fast jedes Gespräch. Rechtlich und praktisch zählt aber vor allem eines: Ist das Grundstück Waldfonds oder nicht?\n\nNicht-Waldgrundstück mit Vegetation: eine von Sträuchern überwucherte Weide, ein verwahrloster Obstgarten, ein innerörtliches Grundstück mit wild gewachsenen Bäumen, eine brachliegende landwirtschaftliche Fläche. Hier sprechen wir von Vegetationsräumung — eine Arbeit, die Sie als Eigentümer in der Regel ohne forstliche Genehmigungen durchführen können. Vegetation fällen, Baumstümpfe roden, Wurzeln fräsen, einebnen — und das Grundstück ist bereit für Bau oder Landwirtschaft. Für einzelne Bäume im Innenbereich verlangen manche Gemeinden eine Fällgenehmigung — ein kurzer Gang zum Rathaus schafft Klarheit.\n\nWaldfonds: Ist das Grundstück in den Dokumenten als Wald (nationaler Waldfonds) eingetragen, ändern sich die Regeln radikal. Die Herausnahme aus dem Waldfonds ist ein Ausnahmeverfahren — langwierig, teuer und mit Kompensationen —, und das Fällen ohne dieses Verfahren ist eine Straftat, auch für den Eigentümer. Hier gibt es keine Abkürzungen: Jeder Eingriff läuft über das Forstamt und die Forsteinrichtung.\n\nSo finden Sie heraus, wo Sie stehen: Prüfen Sie im Grundbuchauszug die Nutzungsart (Wald / Weide / Acker / Hof-Bauland). Im Zweifel fragen Sie das örtlich zuständige Forstamt — kostenlos und schnell.\n\nWas eine professionelle Grundstücksräumung umfasst: Fällen und Häckseln der Vegetation, Stockrodung (Ziehen oder Fräsen — das Fräsen zerkleinert den Stumpf unter Bodenniveau, ohne Krater), Sammeln und Verwerten des Holzmaterials, abschließendes Einebnen. Mit den richtigen Maschinen ist ein Hausgrundstück in Tagen geräumt, nicht in Wochen.\n\nWir übernehmen die [Räumung und Rodung](/servicii/curatare-terenuri) von Nicht-Waldgrundstücken ohne Mindestfläche — vom Hof mit ein paar Bäumen bis zu ganzen Hektaren. Und sollte sich Ihr Grundstück als Waldfonds erweisen, sagen wir es Ihnen offen und verweisen Sie auf das korrekte Verfahren — statt auf eine Arbeit, die Sie in Schwierigkeiten bringt.",
                    "\"I want to clear a plot of land\" — that's how almost every conversation starts. But legally and practically, one thing matters above all: is the land registered forest or not?\n\nNon-forest land with vegetation: a pasture overrun by shrubs, an abandoned orchard, an urban plot with self-seeded trees, farmland left fallow. Here we are talking about vegetation clearing — work you can generally do as the owner without forestry permits. Cut the vegetation, pull the stumps, grind the roots, level the ground — and the land is ready for construction or agriculture. For isolated trees on urban land, some town halls require a felling approval — a quick trip to the town hall will clear it up.\n\nForest land: if the plot is registered as forest (the national forest fund), the rules change radically. Removing land from the forest fund is an exceptional procedure — long, costly and with compensations — and cutting without it is a criminal offence, owner or not. There are no shortcuts here: any intervention goes through the forest district office and the management plan.\n\nHow to find out where you stand: check the land registry extract under land use (forest / pasture / arable / residential). If in doubt, ask the forest district office for the area — free and fast.\n\nWhat professional land clearing involves: cutting and chipping the vegetation, removing stumps (pulling or grinding — grinding shreds the stump below ground level, with no craters), collecting and making use of the timber, and final levelling. With dedicated machinery, a house plot is cleared in days, not weeks.\n\nWe do [land clearing](/servicii/curatare-terenuri) on non-forest land with no minimum area — from a yard with a few trees to whole hectares — and if your land turns out to be registered forest, we tell you straight and point you to the correct procedure, not to a job that lands you in trouble.",
                ),
                'categorie' => 'ghid',
                'imagine' => '/images/galle/proiecte/forwarder-drum-wide.webp',
                'published_at' => now()->subDays(2),
                'is_published' => true,
            ],
        ];

        foreach ($rows as $row) {
            Articol::updateOrCreate(['slug' => $row['slug']], $row);
        }

        $this->seedFromDataFiles();
    }

    /**
     * Articolele extinse: metadatele vin din blog.json, corpul (markdown RO)
     * din data/blog/{slug}.md. DE/EN raman null — front-end-ul face fallback pe RO.
     * Imaginea se seteaza doar daca fisierul exista in public/ (altfel null,
     * iar slug-ul e listat in docs/blog-imagini-necesare.md).
     */
    private function seedFromDataFiles(): void
    {
        $json = file_get_contents(database_path('seeders/data/blog.json'));
        /** @var array<int, array<string, string>> $meta */
        $meta = $json === false ? [] : (array) json_decode($json, true);

        foreach (array_values($meta) as $i => $articol) {
            $continutPath = database_path("seeders/data/blog/{$articol['slug']}.md");
            if (! is_file($continutPath)) {
                continue;
            }

            $imagine = "/images/blog/{$articol['slug']}.webp";
            if (! is_file(public_path(ltrim($imagine, '/')))) {
                $imagine = null;
            }

            Articol::updateOrCreate(['slug' => $articol['slug']], [
                'titlu' => ['ro' => $articol['titlu']],
                'excerpt' => ['ro' => $articol['excerpt']],
                'continut' => ['ro' => trim((string) file_get_contents($continutPath))],
                'categorie' => $articol['categorie'],
                'imagine' => $imagine,
                // Esalonat, inaintea celor 6 articole istorice (34..2 zile).
                'published_at' => now()->subDays(70 - $i * 3),
                'is_published' => true,
            ]);
        }
    }
}
